### ISSUE TITLE
input files

### ISSUE THREAD

**Issue by bioteksampath** [roblanf/minion_qc#30]
Hi,

I wonder I can ask this here.
But my minion runs did not produce sequence_summary.txt files through live base-calling option and only the fast5 and fastq files. can you please guide me how to get the summary file from the available data (fast5 / fastq files).

Thanks a lot
S

**Comment by roblanf** [comment]
Albacore 2.x will generate those files for you. Sounds like you'll probably just need to run the basecalling yourself to get that. I'll talk to the MinION folks and see if it's possible for them to output a sequencing_summary.txt file from the live basecalling.

Cheers,

Rob

**Comment by bioteksampath** [comment]
Thanks, Rob...much appreciated!
