### ISSUE TITLE
Can't successfully run the examples 

### ISSUE THREAD

**Issue by LinXialab** [roblanf/minion_qc#39]
Hi, 
I'm try to run the script just on example data as followed:
Rscript MinIONQC.R  -i example_input -o ./ -p 2
(The version of my R is 3.4.3)

But it is not successful, and i got some error information as followed:

INFO [2018-09-29 15:54:39] **** Analysing the following files ****
INFO [2018-09-29 15:54:39] /home/xialin/tools/minion_qc-master/example_input//RB7_A2/sequencing_summary.txt
INFO [2018-09-29 15:54:39] /home/xialin/tools/minion_qc-master/example_input//RB7_D3/sequencing_summary.txt
INFO [2018-09-29 15:54:39] Loading input file: /home/xialin/tools/minion_qc-master/example_input//RB7_A2/sequencing_summary.txt
INFO [2018-09-29 15:54:39] Loading input file: /home/xialin/tools/minion_qc-master/example_input//RB7_D3/sequencing_summary.txt
INFO [2018-09-29 15:54:46] RB7_A2: creating output directory:.//RB7_A2
INFO [2018-09-29 15:54:46] RB7_A2: summarising input file for flowcell
INFO [2018-09-29 15:54:47] RB7_A2: plotting length histogram
INFO [2018-09-29 15:54:48] RB7_D3: creating output directory:.//RB7_D3
INFO [2018-09-29 15:54:48] RB7_D3: summarising input file for flowcell
INFO [2018-09-29 15:54:49] RB7_D3: plotting length histogram
INFO [2018-09-29 15:54:49] RB7_A2: plotting mean Q score histogram
INFO [2018-09-29 15:54:52] RB7_A2: plotting flowcell overview
INFO [2018-09-29 15:54:52] RB7_D3: plotting mean Q score histogram
INFO [2018-09-29 15:54:55] RB7_D3: plotting flowcell overview
INFO [2018-09-29 15:55:24] RB7_A2: plotting flowcell yield over time
INFO [2018-09-29 15:55:30] RB7_A2: plotting flowcell yield by read length
INFO [2018-09-29 15:55:34] RB7_D3: plotting flowcell yield over time
INFO [2018-09-29 15:55:35] RB7_A2: plotting sequence length over time
INFO [2018-09-29 15:55:41] RB7_D3: plotting flowcell yield by read length
INFO [2018-09-29 15:55:46] RB7_D3: plotting sequence length over time
INFO [2018-09-29 15:55:48] **** Analysing data from all flowcells combined ****
Error in rbindlist(results) :
  Item 1 of list input is not a data.frame, data.table or list
Calls: as.data.frame -> rbindlist
Execution halted

Could you please tell me what's the problem, and how can i fix this?
Thank so much!
Sincerely.

**Comment by roblanf** [comment]
Hi, 

Can you double check that you are using the latest version from github? When I run the same command (perhaps obviously!) I don't get this error. 

A few more questions:

1. Can you check the output that you get for the single flowcells. Is it all there? Based on your commandline, it should be there in two folders (`RB7_A2` and `RB7_D3`) in the directory you run the script from. The output should be identical to that in the `example_output` file.
2. Can you tell me your OS details?

Thanks,

Rob
