### ISSUE TITLE
Problem with combining flow cell data

### ISSUE THREAD

**Issue by caity-s** [roblanf/minion_qc#44]
Hello Rob,

I am having some problems with the program when it gets to the combining point - individually everything works very smoothly with all the relevant files produced!

INFO [2018-12-19 09:56:47] **** Analysing data from all flowcells combined ****
Error in rbindlist(results) : 
  Item 1 of list input is not a data.frame, data.table or list
Calls: as.data.frame -> rbindlist
Execution halted

Do you know what the issue might be? It is looking at 11 promethion flow cells... so quite a large data set.

Thanks!
Caitlin

**Comment by caity-s** [comment]
My system is a server running biolinux based on Ubuntu 14.04.5.

**Comment by caity-s** [comment]
Scatch that, I think it was a folder structural issue on my side - I had an additional folder in there that may have confused things. It is working on the combined summary file now - though it may be some time... and memory! Thank you for making a very useful tool!

**Comment by roblanf** [comment]
Hi @caity-s, thanks for the report. Any chance you can elaborate on the folders you had in more detail. It would be great if I could make this more intuitive. At the very least I might be able to spit out a useful error. But preferably I'd just make it work without failing at all.

**Comment by caity-s** [comment]
Hello Rob,

I had the 10 folders named by flow cell that each contained a single sequencing_summary.txt file and then there was an additional folder (that I had just called nanopore_qc) that had files within it as <sample_name>_sequencing_summary.txt (so essentially just containing duplicate files of what were in the other folders, just named differently - I was working on something else that needed that layout). The script was pulling in those files too, understandably. I am not sure if the problem was because their names were different, or that they were duplicates, or that there was an unexpected number of sequencing_summary.txt files in that one folder. Either way, I wasn't following the folder structure that is clearly described in the documentation...

Thank you and Happy New Year!
Caitlin
