### ISSUE TITLE
Problem running from guppy demuxed summary file

### ISSUE THREAD

**Issue by peflanag** [roblanf/minion_qc#46]
Hi All,

I'm wondering if you can help me. I am trying to run my barcode_summary.txt file generated from demux'ing with Guppy. Any ideas why it failed? Or maybe I cant use this file and I didn't notice in the literature.

Cheers,

Peter

![Screenshot 2019-04-10 at 11 23 28](https://user-images.githubusercontent.com/32863969/55871788-57990400-5b83-11e9-879d-fdaf96fb10a3.png)

**Comment by roblanf** [comment]
Hi Peter,

Any chance you can send me your file (or the first few thousand lines of it if it's really big) off list? If so, I can work on fixing whatever the issue is. Without that, it's tricky to make much progress.

Contact details are here: http://robertlanfear.com/contact

Many thanks,

Rob

**Comment by roblanf** [comment]
Hi Peter,

Thanks for sending the file. The issue here is that the file you're using as input is not a sequencing_summary file. Your file is a summary of the barcoding demultiplexing, and has the following headers (with one line shown for information):

```
read_id	barcode_arrangement	barcode_full_arrangement	barcode_kit	barcode_variant	barcode_score	barcode_front_id	barcode_front_score	barcode_front_refseq	barcode_front_foundseq	barcode_front_foundseq_length	barcode_front_begin_index	barcode_rear_id	barcode_rear_score	barcode_rear_refseq	barcode_rear_foundseq	barcode_rear_foundseq_length	barcode_rear_end_index
67861e16-96cb-4568-badd-7ff4f1b22efc	unclassified	NB06_var1	NB	var1	54.5128	NB06_1st_FWD	54.5128	AGGTTAAGACTACTTTCTGCCTTTGCGAGAACAGCACCT	AGGTTGAGCTACTTTCTGCGCTGAGGAACAACT	33	24	NB06_2nd_REV	43.3778	GGTGCTGTTCTCGCAAAGGCAGAAAGTAGTCTTAACCTTAGCAAT	GGTGCTGTTCTCGCAGCGGCAATAGTGTGCCAACAGTAAT	40	9
```

This doesn't contain any information on the individual sequencing reads. What you're looking for is a file with headers like this:

```
filename	read_id	run_id	channel	start_time	duration	num_events	passes_filtering	template_start	num_events_template	template_duration	num_called_template	sequence_length_template	mean_qscore_template	strand_score_template
rsb0001410_20170609_FNFAH05342_MN22383_mux_scan_Epauciflora_A2_77810_read_116_ch_47_strand.fast5	e2e07125-8285-416b-a6f1-8e5d5f017c82	52b163295bcfff805ebbe566ee02dffe2c40c323	47	388.26959	1.61155	1386	False	0.0	1386	1.61155	1386	10	3.317	-0.0022
```

This contains one row per read, and is what MinionQC uses to generate summaries.

Rob

**Comment by peflanag** [comment]
Cheers Rob. I'll just go with the non demuxed file then since that seems correct. Its a shame about the demuxed guppy one!
