### ISSUE TITLE
Error in rbindlist(results) while processing guppy generated sequencing_summary.txt

### ISSUE THREAD

**Issue by asantat** [roblanf/minion_qc#49]
Hi!

Thanks for the amazing work.
But I have an error trying to process standalone guppy-generated txt files. I have fastq files that belongs to one specimen but created in three MinION runs and after that basecalled into the same directory. I run script this way:
$ ~/envs/minionqc/MinIONQC.R -i ./guppy_basecalled/ -o ./minionqc_guppy -p 16 -c FALSE

And I have an output:
`INFO [2020-05-23 09:54:39] 
INFO [2020-05-23 09:54:39] **** Analysing the following files ****
INFO [2020-05-23 09:54:39] ./guppy_basecalled//sequencing_summary.txt
INFO [2020-05-23 09:54:39] ./guppy_basecalled//sequencing_summary.txt.prev
INFO [2020-05-23 09:54:39] Loading input file: ./guppy_basecalled//sequencing_summary.txt
INFO [2020-05-23 09:54:39] Loading input file: ./guppy_basecalled//sequencing_summary.txt.prev
Warning: 1 parsing failure.
    row col   expected    actual                                                     file
1307403  -- 30 columns 3 columns './guppy_basecalled//sequencing_summary.txt.prev'

Warning: 1 parsing failure.
    row col   expected    actual                                                file
1305487  -- 30 columns 3 columns './guppy_basecalled//sequencing_summary.txt'

INFO [2020-05-23 09:54:42] **** Analysing data from all flowcells combined ****
Error in rbindlist(results) : 
  Item 1 of input is not a data.frame, data.table or list
Calls: as.data.frame -> rbindlist
Execution halted`

What was my error and what I have to do to process files correctly.

Best regards
Asan

**Comment by roblanf** [comment]
Hi @asantat,

If you can send me a link so I can download your file, I will take a look. My contact details are https://biology.anu.edu.au/people/academics/robert-lanfear

Obviously, I won't keep your files around once I've debugged the error. I will also try to make sure it gives a more useful error message!

Rob

**Comment by roblanf** [comment]
Hi @asantat, 

Apologies for the long wait. Turns out the problem is very simple, and is covered in the output that the script gives (though this output is *obviously* very unclear, since neither of us knew what was happening until I had time to dig deeper). 

The issue is that line 1305487 of your input file is incomplete, and is missing most columns. If you remove this line, everything works fine.

I'll email you the output files, and I'll leave this issue open until I have improved things by adding a better error message and/or building the script to skip over incomplete lines like this, which I suspect come from issues upstream in Guppy or similar.

Rob

**Comment by roblanf** [comment]
OK, it's now fixed here https://github.com/roblanf/minion_qc/commit/f1b686fd615e0ba861f2e9feef4efdcc1672f5c4#diff-e1caec0b976fab3e28e01837093a06e6. 

This should handle the situation gracefully, like this

```
INFO [2020-06-03 11:08:18] Loading input file: /Users/roblanfear/Desktop/mqc/sequencing_summary.txt
WARN [2020-06-03 11:08:20] There were problems in parsing your input file with the following rows: 
WARN [2020-06-03 11:08:20] 1305487
WARN [2020-06-03 11:08:20] These rows will be ignored for further analysis, please check your input file
```

Thanks again for highlighting the issue.

**Comment by asantat** [comment]
Thank you Rob for the response. It was very helpfull for me. Thank you
again.

Best regards
Asan

ср, 3 июн. 2020 г. в 06:00, roblanf <notifications@github.com>:

**Comment by asantat** [comment]
How do you do?

Thank you for response. I send you files I have processed.
Please follow the link
https://drive.google.com/drive/folders/1QoemS7J1bbzSxj_dthBadax4isEqT5Wr?usp=sharing

Best regards
Asan

сб, 6 июн. 2020 г. в 21:10, Asan Emirsale <asantaraqtasli@gmail.com>:
