### ISSUE TITLE
Font could not be loaded

### ISSUE THREAD

**Issue by FredericBGA** [roblanf/minion_qc#6]
Hello

using R

> R
> R version 3.2.0 (2015-04-16) -- "Full of Ingredients"
> Copyright (C) 2015 The R Foundation for Statistical Computing
> Platform: x86_64-unknown-linux-gnu (64-bit)

it fails:

> tail -f minion_QC.log
> Loading required package: viridisLite
> [1] "Creating output directory"
> [1] "Loading and summarising input file"
> [1] "Plotting length histogram"
> Error in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
>   X11 font -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 1 at size 15 could not be loaded
> Calls: print ... <Anonymous> -> widthDetails -> widthDetails.text -> grid.Call
> Execution halted

It works when I add this to the beginning of the file

`options(bitmapType='cairo')`

**Comment by roblanf** [comment]
Thanks for the heads up - not sure how to fix this (without forcing a font), since I only use default fonts. Might work to update to the latest version of R as well. Closing for now.
