### ISSUE TITLE
minion_qc fails with data frame reading error

### ISSUE THREAD

**Issue by GeoMicroSoares** [roblanf/minion_qc#9]
@roblanf here's what I'm getting, still not sure why:

> Loading required package: viridisLite
> [1] "Creating output directory"
> [1] "Loading and summarising input file"
> Error in `$<-.data.frame`(`*tmp*`, "flowcell", value = "NA") :
>   replacement has 1 row, data has 0
> Calls: load_summary -> $<- -> $<-.data.frame
> Execution halted

What should I do?
Thanks

**Comment by roblanf** [comment]
I think this should be fixed in the latest update - in this case it's (probably, not sure) because you don't have any reads with Q>10. Can you let me know here if the update fixes this. If not, if you can send me your input file off-list, I can take a look. (http://www.robertlanfear.com/contact/)

**Comment by roblanf** [comment]
This should be fixed in the latest release.
